"""create users, data

Revision ID: acf518fda0e0
Revises: 
Create Date: 2018-04-03 15:59:37.722098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf518fda0e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('current_skill', sa.Integer(), nullable=True),
    sa.Column('mastery', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_created_date'), 'topic', ['created_date'], unique=False)
    op.create_index(op.f('ix_topic_filename'), 'topic', ['filename'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('before_skill', sa.Integer(), nullable=True),
    sa.Column('after_skill', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_review_date'), 'review', ['review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_review_date'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topic_filename'), table_name='topic')
    op.drop_index(op.f('ix_topic_created_date'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
