"""Added last_study_date field in Topic

Revision ID: d64de2ff2c6a
Revises: 9cf6c873fd85
Create Date: 2018-04-04 17:36:40.994658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64de2ff2c6a'
down_revision = '9cf6c873fd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('last_study_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_topic_last_study_date'), 'topic', ['last_study_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_last_study_date'), table_name='topic')
    op.drop_column('topic', 'last_study_date')
    # ### end Alembic commands ###
