"""Adding default to column Topic.current_skill

Revision ID: edf20c652b87
Revises: f6ec74a577c0
Create Date: 2018-04-11 17:31:25.523151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf20c652b87'
down_revision = 'f6ec74a577c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('review', 'test')
    op.create_index(op.f('ix_topic_current_skill'), 'topic', ['current_skill'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_current_skill'), table_name='topic')
    op.add_column('review', sa.Column('test', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
