"""test

Revision ID: f6ec74a577c0
Revises: c6880f14af04
Create Date: 2018-04-11 14:34:17.178300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ec74a577c0'
down_revision = 'c6880f14af04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
