"""test

Revision ID: f79643ac25f8
Revises: d64de2ff2c6a
Create Date: 2018-04-11 14:02:13.768557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79643ac25f8'
down_revision = 'd64de2ff2c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('start_skill', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'start_skill')
    # ### end Alembic commands ###
